### ISSUE TITLE
No module named 'pyfreenas'

### ISSUE THREAD

**Issue by soaringswine** [sdwilsh/hass-truenas#1]
Hi,

I installed this integration via HACS, but I receive this error in my hass.io logs and no TrueNAS entities ever appear: 

```
Logger: homeassistant.setup
Source: setup.py:280
First occurred: 1:14:02 AM (1 occurrences)
Last logged: 1:14:02 AM

Unable to prepare setup for platform truenas.sensor: Platform not found (No module named 'pyfreenas').
```

**Comment by gitricohub** [comment]
I'm having the same issue...any idea what is causing this?

**Comment by MATN92** [comment]
Same issue... I've got Home Assistant OS 5.9 (2020.12.7) with TrueNAS-12.0-U1

**Comment by sdwilsh** [comment]
I somehow missed this in my gmail inbox, but I'll get this fixed up today.
