### ISSUE TITLE
Unload entry references invalid key

### ISSUE THREAD

**Issue by MatthewFlamm** [sdwilsh/hass-truenas#11]
Error traceback when unloading entry:

```
Traceback (most recent call last):
  File "/mnt/usbdrive/homeassistant/custom/home-assistant/homeassistant/config_entr
ies.py", line 321, in async_unload
    result = await component.async_unload_entry(hass, self)  # type: ignore
  File "/mnt/usbdrive/homeassistant/custom/home-assistant/config/custom_components/
truenas/__init__.py", line 113, in async_unload_entry
    await hass.data[DOMAIN]["machine"]._client.close()
KeyError: 'machine'
```

Data is stored inside the `entry.entry_id`

https://github.com/sdwilsh/hass-truenas/blob/9202bc8688c8dedbe6d65c835eecc13be91b5a0b/custom_components/truenas/__init__.py#L86

But it is not used in the unload
https://github.com/sdwilsh/hass-truenas/blob/9202bc8688c8dedbe6d65c835eecc13be91b5a0b/custom_components/truenas/__init__.py#L113

**Comment by sdwilsh** [comment]
That line 113 call isn't even right anymore.  The client library has a proper close library that will be important to utilize as well:
https://github.com/sdwilsh/aiotruenas-client/blob/main/aiotruenas_client/websockets/machine.py#L90
