### ISSUE TITLE
Integration incompatible with HA 2023.4.2 because of websockets constraint

### ISSUE THREAD

**Issue by slovdahl** [sdwilsh/hass-truenas#184]
The integration stopped working after updating to HA 2023.4.2 because the `websockets` dependency constraint prohibits it from being installed.

```
2023-04-09 08:57:46.888 ERROR (SyncWorker_5) [homeassistant.util.package] Unable to install package aiotruenas-client==0.9.0: ERROR: Cannot install aiotruenas-client==0.9.0 because these package versions have conflicting dependencies.
ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts
```

The `websockets` version was bumped to 11.0.1: https://github.com/home-assistant/core/pull/90901

**Comment by sdwilsh** [comment]
I guess now is a good time to make it easier to keep deps updated in that repository :)

**Comment by sdwilsh** [comment]
That was a lot of work to get everything updated, but I just verified that the 0.4.0 release works with 2023.4.2.  Thanks for the report!
