### ISSUE TITLE
Dependency issue with HA 2024.12

### ISSUE THREAD

**Issue by james-fry** [sdwilsh/hass-truenas#216]
The addon does not start on HA 2024.12.

HA versions:
Core 2024.12.1
Supervisor 2024.11.4
Operating System 14.0
Frontend 20241127.6

HA Logs:

Logger: homeassistant.setup
Source: setup.py:269
First occurred: 12:44:10 PM (1 occurrences)
Last logged: 12:44:10 PM

Setup failed for custom integration 'truenas': Requirements for truenas not found: ['aiotruenas-client==0.10.0'].

Logger: homeassistant.util.package
Source: util/package.py:152
First occurred: 12:44:10 PM (3 occurrences)
Last logged: 12:44:10 PM

Unable to install package aiotruenas-client==0.10.0: × No solution found when resolving dependencies: ╰─▶ Because aiotruenas-client==0.10.0 depends on websockets==11.0.1 and websockets>=13.1, we can conclude that aiotruenas-client==0.10.0 cannot be used. And because you require aiotruenas-client==0.10.0, we can conclude that your requirements are unsatisfiable.

**Comment by abertolin** [comment]
Same problem here ...

**Comment by adorobis** [comment]
The problem is most likely simple. HA 2024.12 comes with the new python version...

**Comment by abertolin** [comment]
This works: https://github.com/tomaae/homeassistant-truenas
I'll move to it.

**Comment by sdwilsh** [comment]
yeah, sorry y'all.  I've stopped using this myself, and I should probably archive this.  The other one looks more active in terms of community too.
