### ISSUE TITLE
Support API Token Authentication

### ISSUE THREAD

**Issue by sdwilsh** [sdwilsh/hass-truenas#4]
We should even encourage it over username/password authentication.

**Comment by sdwilsh** [comment]
@MatthewFlamm, you may be interested in tackling this!

**Comment by MatthewFlamm** [comment]
Cool!  I will take a look.

**Comment by MatthewFlamm** [comment]
Some thoughts here.  Currently the config flow creates config entries with data of `host`, `password`, `username`, and `name`.  At the absolute very least, we need to add an `api_key`.  I think it is ideal if we split the config flow into two steps.  The first asks which authentication method is to be used, the second collects the authentication info, i.e. either username/password or api_key.  In this case it is also natural to store the `authentication_method` in the config entry, which makes the setup easier later.  But it isn't required.

We should migrate all existing config entries to a version 2, with the additional item(s) in the config entry data.  I would feel more confident if we first added tests for the existing behavior, then added tests to make sure the migration works properly.  See #8 about tests.

**Comment by sdwilsh** [comment]
This sounds like a great plan.  I don't want to toss username/password yet since this, in theory, still works with FreeNAS, which is still supported, but has no token auth.
