### ISSUE TITLE
Add tests

### ISSUE THREAD

**Issue by MatthewFlamm** [sdwilsh/hass-truenas#8]
I somewhat hesitate to suggest this, as it uses my own project, but it would help me contribute more competently if tests are added.  Please feel free to decline since it is not trivial to add tests 
for homeassistant code, and, more importantly, tests for custom components is not supported by homeassistant directly.

See https://github.com/MatthewFlamm/pytest-homeassistant-custom-component.

If this is okay, I can add it to your requirements and CI with a starter of tests for the config flow.

**Comment by sdwilsh** [comment]
I saw you library for that, and thought it would be interesting.  Given that I can go months between looking at projects, I absolutely love tests, and would support this.

Every time I touch this integration, I start to worry about what I might be breaking, so I'll be more than happy to add tests if you do the initial setup work.
